AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This script creates SnowDesignatedAccountAccessRole (Used by ServiceNow User)
  IAM role in member accounts. This will be establish trust between management
  or designated account with all member accounts. 
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Management or Designated Member Account Details
        Parameters:
          - ACNNBR
      - Label:
          default: S3 Bucket Details
        Parameters:
          - S3Bucket
      - Label:
          default: Service Now User Details
        Parameters:
          - ServiceNowUserName
    ParameterLabels:
      ACNNBR:
        default: Enter  Management or Designated Member Account Id
      S3Bucket:
        default: S3 Bucket Name
Parameters:
  ACNNBR:
    Type: String
    MaxLength: 12
    MinLength: 12
    Description: >-
      If you are creating ServiceNow user in Management Account, then enter
      Management Account ID. If you are creating ServiceNow user in Designated
      Member account, then enter the designated member account ID.
  S3Bucket:
    Type: String
    Description: >-
      Enter the S3 bucket name you have created/chosen to get SendCommand
      output.
  ServiceNowUserName:
    Type: String
    Description: >-
      Enter the name of the ServiceNow User that was created as part of the setup.
Resources:
  SnowOrganizationAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SnowOrganizationAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${ACNNBR}:user/${ServiceNowUserName}
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SnowOrganizationAccountAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ServiceNowUserReadOnlyAccessOrg
                Effect: Allow
                Action:
                  - organizations:DescribeOrganization
                  - organizations:ListAccounts
                  - organizations:ListRoots
                  - organizations:ListAccountsForParent
                  - organizations:ListOrganizationalUnitsForParent
                  - organizations:DescribeOrganizationalUnit
                  - organizations:ListTagsForResource 
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessConfig
                Effect: Allow
                Action:
                  - config:ListDiscoveredResources
                  - config:SelectResourceConfig
                  - config:BatchGetResourceConfig
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessConfigAgg
                Effect: Allow
                Action:
                  - config:DescribeConfigurationAggregators
                  - config:SelectAggregateResourceConfig
                  - config:BatchGetAggregateResourceConfig
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessEC2
                Effect: Allow
                Action:
                  - ec2:DescribeRegions
                  - ec2:DescribeImages
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceTypes
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessSSM
                Effect: Allow
                Action:
                  - ssm:DescribeInstanceInformation
                  - ssm:ListInventoryEntries
                  - ssm:GetInventory
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessTag
                Effect: Allow
                Action:
                  - tag:GetResources
                Resource: '*'
              - Sid: ServiceNowUserReadOnlyAccessIAM
                Effect: Allow
                Action:
                  - iam:CreateAccessKey
                  - iam:DeleteAccessKey
                Resource: 
                  - !Sub arn:${AWS::Partition}:iam::${ACNNBR}:user/${ServiceNowUserName}
              - Sid: ServiceNowSendCommandAccess
                Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource:
                  - !Sub arn:${AWS::Partition}:ec2:*:${AWS::AccountId}:instance/*
                  - !Sub arn:${AWS::Partition}:ssm:*:${AWS::AccountId}:document/SG-AWS*
              - Sid: ServiceNowS3BucketAccess
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${S3Bucket}/*
                  - !Sub arn:${AWS::Partition}:s3:::${S3Bucket}
Outputs:
  ServiceNowUserRoleARN:
    Description: ARN of ServiceNow Designated Account Access Role
    Value: !GetAtt
      - SnowOrganizationAccountAccessRole
      - Arn